name: Release Workflow

on:
  workflow_call:
    inputs:
      gh_repository_owner:
        required: true
        type: string
      gh_event_name:
        required: true
        type: string
      gh_ref:
        required: true
        type: string
      registry:
        required: true
        type: string
      image_repo_tag:
        required: true
        type: string
    secrets:
      QUAY_USERID:
        required: true
      QUAY_PASSWORD:
        required: true
    
    outputs:
      digest:
        description: "Digest"
        value: ${{ jobs.release.outputs.digest }}

jobs:
  release:
    runs-on: ubuntu-latest

    outputs:
      digest: ${{ steps.release.outputs.digest }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after a couple of runs

      - name: Image Releaser
        id: release
        uses: ortelius/ms-release-action@8d3e173e28e5614e6d26f43d447a5c12baf384f2 # v1.0.0
        with:
          gh_repository_owner: ${{ inputs.gh_repository_owner }}
          gh_event_name: ${{ inputs.gh_event_name }}
          gh_ref: ${{ inputs.gh_ref }}
          registry: ${{ inputs.registry }}
          image_repo_tag: ${{ inputs.image_repo_tag }}
          QUAY_USERID: ${{ secrets.QUAY_USERID }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          
